# Generated by Django 3.2.4 on 2022-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('rid', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pic', models.ImageField(null=True, upload_to='Profile/')),
                ('ryear', models.CharField(max_length=40)),
                ('mob', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
