# Generated by Django 3.2.4 on 2022-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0002_auto_20220922_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('userid', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
