# Generated by Django 3.2.4 on 2022-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0004_alter_guardregistration_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/Profile/'),
        ),
    ]
