# Generated by Django 3.2.4 on 2022-09-22 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0006_requestpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpass',
            name='permittime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
