# Generated by Django 3.2.4 on 2022-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0007_requestpass_permittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='rid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
