# Generated by Django 3.2.4 on 2022-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0008_alter_registration_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardregistration',
            name='guardid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
