# Generated by Django 3.2.4 on 2022-09-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0009_alter_guardregistration_guardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardregistration',
            name='guardid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
