# Generated by Django 3.2.4 on 2022-09-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0010_alter_guardregistration_guardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpass',
            name='permittime',
            field=models.DateTimeField(),
        ),
    ]
