# Generated by Django 3.2.4 on 2022-09-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0011_alter_requestpass_permittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpass',
            name='permittime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
